name: Demian Lee
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.34726740047335625
  lightness: 0.5809112426359206
  saturation: 0.9208834762685001
  rhythmicContrast: 0.4602853483520448
purpose: []
